import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// This gets called on every request
export async function getServerSideProps() {
  const min = 47144;
  const max = 48143;

  const randNumber = Math.floor(Math.random() * (max - min + 1) + min);
  const res = await fetch(
    `https://personal-mongo.herokuapp.com/quotes/${randNumber}`
  );

  const data = await res.json();

  return { props: { data } };
}

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next js Test App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>{data.quote}</p>
        <p>
          <strong>{data.author}</strong>
        </p>
      </main>
    </div>
  );
}
